# Generated by Django 4.2.7 on 2024-04-23 01:54

from django.db import migrations, models
import multimedia.models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="processed_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=multimedia.models.PathAndRename("processed_videos"),
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
